### ISSUE TITLE
Manual - Environment configuration 에 질문이 있습니다.

### ISSUE THREAD

**Issue by h-dyeon** [CAU-OSS-2019/Korean-tag-recommeder#18]
README.md를 보고 설치를 했습니다.

1.  
<code> $ pip install --upgrade gensim </code> 
<code> $ pip install --upgrade pip </code> 
<code> $ conda -c conda-forge install jpype1 </code> 
<code> $ pip install konlpy </code> 

![설치중1](https://user-images.githubusercontent.com/31642303/59271013-e8788280-8c8d-11e9-8638-4b113359dd2a.png)
관리자 권한으로 cmd를 다시 실행하여 아래와 같이 입력했습니다.
![설치중2](https://user-images.githubusercontent.com/31642303/59271015-e9a9af80-8c8d-11e9-81f6-f71b532b51bf.png)

2.  
<code> $ conda install -c conda-forge gensim 
</code> 
<code> $ pip install --upgrade pip </code> 
<code> $ conda -c conda-forge install jpype1 </code> 
<code> $ pip install konlpy </code> 

![콘다1](https://user-images.githubusercontent.com/31642303/59271034-f4fcdb00-8c8d-11e9-9c70-1301276a54b1.png)
![콘다2](https://user-images.githubusercontent.com/31642303/59271036-f62e0800-8c8d-11e9-9554-973d61112e77.png)
![콘다3](https://user-images.githubusercontent.com/31642303/59271041-f75f3500-8c8d-11e9-8e85-f4253afc6b6e.png)

두가지 모두 <code> $ conda -c conda-forge install jpype1 </code> 를 입력했을때
<code>CommandNotFoundError: No command 'conda conda-forge'.</code> 라는 오류가 떴습니다.
제가 뭔가를 놓치고 있는건가요 혹은 readme가 잘못된 걸까요..?

gui는 실행이 되지만 
막상 "계단 그림자 기다리는 중. 필카의 묘미." 로 예시를 입력하고 
process버튼을 누르면
가장 마지막 사진의 하단부처럼 에러가 뜹니다. 

답변 해주시면 감사드리겠습니다.

**Comment by EJLEE5826** [comment]
저희는 Anaconda Python 3.6 환경에서 제작했기에, Readme가 아나콘다 환경 위주로 작성되었습니다.
Readme에서 해당 설명을 추가하겠습니다.

오류를 보니 KoNLPy를 위한 JAVA_HOME 설정이 되어있지 않은 듯 합니다.
[이곳](https://konlpy-ko.readthedocs.io/ko/v0.4.3/install/#id2) 을 참고하여 KoNLPy 환경 설정을 완료하여 주세요. JDK software 설치와 JPype1 다운로드, 설치가 필요합니다.

**Comment by EJLEE5826** [comment]
Readme를 수정했습니다. 확인하여 설치해주시면 감사하겠습니다.
